/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: {
    en: string;
    bg?: string;
    es?: string;
  };
};

export type Tool = {
  _id: string;
  _type: "tool";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroBg: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type ToolReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tool";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  link?: string;
  order?: number;
  tools?: Array<
    {
      _key: string;
    } & ToolReference
  >;
  description?: {
    en: string;
    bg?: string;
    es?: string;
  };
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  desktopImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mobileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Thought = {
  _id: string;
  _type: "thought";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: {
    en: string;
    bg?: string;
    es?: string;
  };
  description?: {
    en: string;
    bg?: string;
    es?: string;
  };
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: {
      en?: string;
      bg?: string;
      es?: string;
    };
    _type: "image";
  };
  slug?: {
    en: Slug;
    bg?: Slug;
    es?: Slug;
  };
  metaTitle?: {
    en?: string;
    bg?: string;
    es?: string;
  };
  metaDescription?: {
    en?: string;
    bg?: string;
    es?: string;
  };
  date: string;
  faq?: Array<{
    question?: {
      en: string;
      bg?: string;
      es?: string;
    };
    answer?: {
      en: string;
      bg?: string;
      es?: string;
    };
    _type: "faqItem";
    _key: string;
  }>;
  body?: {
    en?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            blank?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }
    >;
    bg?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            blank?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }
    >;
    es?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            blank?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }
    >;
  };
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Service
  | Tool
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | ToolReference
  | ServiceReference
  | Project
  | Thought
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/lib/queries.ts
// Variable: THOUGHT_CARDS_QUERY
// Query: *[_type == "thought" && defined(slug.en.current)] | order(date desc) {    "enSlug": slug.en.current,    slug,    title,    description,    date,    mainImage  }
export type THOUGHT_CARDS_QUERY_RESULT = Array<{
  enSlug: string;
  slug: {
    en: Slug;
    bg?: Slug;
    es?: Slug;
  };
  title: {
    en: string;
    bg?: string;
    es?: string;
  } | null;
  description: {
    en: string;
    bg?: string;
    es?: string;
  } | null;
  date: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: {
      en?: string;
      bg?: string;
      es?: string;
    };
    _type: "image";
  };
}>;

// Source: ../src/lib/queries.ts
// Variable: THOUGHT_PATHS_QUERY
// Query: *[_type == "thought" && defined(slug.en.current)]{    "enSlug": slug.en.current,    slug  }
export type THOUGHT_PATHS_QUERY_RESULT = Array<{
  enSlug: string;
  slug: {
    en: Slug;
    bg?: Slug;
    es?: Slug;
  };
}>;

// Source: ../src/lib/queries.ts
// Variable: THOUGHT_QUERY
// Query: *[_type == "thought" && slug.en.current == $enSlug][0]{    "enSlug": slug.en.current,    slug,    title,    description,    metaTitle,    metaDescription,    date,    "updatedAt": _updatedAt,    mainImage,    "body": body{      "en": en[]{ ..., _type == "image" => { ..., "asset": asset->{ url } } },      "bg": bg[]{ ..., _type == "image" => { ..., "asset": asset->{ url } } },      "es": es[]{ ..., _type == "image" => { ..., "asset": asset->{ url } } }    },    faq  }
export type THOUGHT_QUERY_RESULT = {
  enSlug: string | null;
  slug: {
    en: Slug;
    bg?: Slug;
    es?: Slug;
  } | null;
  title: {
    en: string;
    bg?: string;
    es?: string;
  } | null;
  description: {
    en: string;
    bg?: string;
    es?: string;
  } | null;
  metaTitle: {
    en?: string;
    bg?: string;
    es?: string;
  } | null;
  metaDescription: {
    en?: string;
    bg?: string;
    es?: string;
  } | null;
  date: string;
  updatedAt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: {
      en?: string;
      bg?: string;
      es?: string;
    };
    _type: "image";
  };
  body: {
    en: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            blank?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset: {
            url: string;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }
    > | null;
    bg: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            blank?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset: {
            url: string;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }
    > | null;
    es: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            blank?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset: {
            url: string;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }
    > | null;
  } | null;
  faq: Array<{
    question?: {
      en: string;
      bg?: string;
      es?: string;
    };
    answer?: {
      en: string;
      bg?: string;
      es?: string;
    };
    _type: "faqItem";
    _key: string;
  }> | null;
} | null;

// Source: ../src/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    "heroBg": { "url": heroBg.asset->url }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  heroBg: {
    url: string | null;
  };
} | null;

// Source: ../src/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc, _createdAt asc) {    _id,    title,    link,    description,    "services": services[]->title,    "tools": tools[]->name,    "desktopImage": desktopImage{      ...,      "width":  asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height    },    "mobileImage": mobileImage{      ...,      "width":  asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height    }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  link: string | null;
  description: {
    en: string;
    bg?: string;
    es?: string;
  } | null;
  services: Array<{
    en: string;
    bg?: string;
    es?: string;
  } | null> | null;
  tools: Array<string> | null;
  desktopImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    width: number | null;
    height: number | null;
  };
  mobileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    width: number | null;
    height: number | null;
  };
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "thought" && defined(slug.en.current)] | order(date desc) {\n    "enSlug": slug.en.current,\n    slug,\n    title,\n    description,\n    date,\n    mainImage\n  }\n': THOUGHT_CARDS_QUERY_RESULT;
    '\n  *[_type == "thought" && defined(slug.en.current)]{\n    "enSlug": slug.en.current,\n    slug\n  }\n': THOUGHT_PATHS_QUERY_RESULT;
    '\n  *[_type == "thought" && slug.en.current == $enSlug][0]{\n    "enSlug": slug.en.current,\n    slug,\n    title,\n    description,\n    metaTitle,\n    metaDescription,\n    date,\n    "updatedAt": _updatedAt,\n    mainImage,\n    "body": body{\n      "en": en[]{ ..., _type == "image" => { ..., "asset": asset->{ url } } },\n      "bg": bg[]{ ..., _type == "image" => { ..., "asset": asset->{ url } } },\n      "es": es[]{ ..., _type == "image" => { ..., "asset": asset->{ url } } }\n    },\n    faq\n  }\n': THOUGHT_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    "heroBg": { "url": heroBg.asset->url }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "project"] | order(order asc, _createdAt asc) {\n    _id,\n    title,\n    link,\n    description,\n    "services": services[]->title,\n    "tools": tools[]->name,\n    "desktopImage": desktopImage{\n      ...,\n      "width":  asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height\n    },\n    "mobileImage": mobileImage{\n      ...,\n      "width":  asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height\n    }\n  }\n': PROJECTS_QUERY_RESULT;
  }
}
